var deck = [
    {"card": "1", "value": "1", "text": "Move from START or move forward 1."},
    {"card": "2", "value": "1", "text": "Move from START or move forward 1."},
    {"card": "3", "value": "1", "text": "Move from START or move forward 1."},
    {"card": "4", "value": "1", "text": "Move from START or move forward 1."},
    {"card": "5", "value": "1", "text": "Move from START or move forward 1."},
    {"card": "6", "value": "2", "text": "Move from START 2 or move forward 2.  Draw again."},
    {"card": "7", "value": "2", "text": "Move from START 2 or move forward 2.  Draw again."},
    {"card": "8", "value": "2", "text": "Move from START 2 or move forward 2.  Draw again."},
    {"card": "9", "value": "2", "text": "Move from START 2 or move forward 2.  Draw again."},
    {"card": "10", "value": "3", "text": "Move forward 3."},
    {"card": "11", "value": "3", "text": "Move forward 3."},
    {"card": "12", "value": "3", "text": "Move forward 3."},
    {"card": "13", "value": "3", "text": "Move forward 3."},
    {"card": "14", "value": "4", "text": "Move backwards 4."},
    {"card": "15", "value": "4", "text": "Move backwards 4."},
    {"card": "16", "value": "4", "text": "Move backwards 4."},
    {"card": "17", "value": "4", "text": "Move backwards 4."},
    {"card": "18", "value": "5", "text": "Move forward 5."},
    {"card": "19", "value": "5", "text": "Move forward 5."},
    {"card": "20", "value": "5", "text": "Move forward 5."},
    {"card": "21", "value": "5", "text": "Move forward 5."},
    {"card": "22", "value": "7", "text": "Move forward 7 or split the move between 2 pawns"},
    {"card": "23", "value": "7", "text": "Move forward 7 or split the move between 2 pawns"},
    {"card": "24", "value": "7", "text": "Move forward 7 or split the move between 2 pawns"},
    {"card": "25", "value": "7", "text": "Move forward 7 or split the move between 2 pawns"},
    {"card": "26", "value": "8", "text": "Move forward 8."},
    {"card": "27", "value": "8", "text": "Move forward 8."},
    {"card": "28", "value": "8", "text": "Move forward 8."},
    {"card": "29", "value": "8", "text": "Move forward 8."},
    {"card": "30", "value": "10", "text": "Move forward 10 or move backward 1."},
    {"card": "31", "value": "10", "text": "Move forward 10 or move backward 1."},
    {"card": "32", "value": "10", "text": "Move forward 10 or move backward 1."},
    {"card": "33", "value": "10", "text": "Move forward 10 or move backward 1."},
    {"card": "34", "value": "11", "text": "Move forward 11 or change places with an opponent."},
    {"card": "35", "value": "11", "text": "Move forward 11 or change places with an opponent."},
    {"card": "36", "value": "11", "text": "Move forward 11 or change places with an opponent."},
    {"card": "37", "value": "11", "text": "Move forward 11 or change places with an opponent."},
    {"card": "38", "value": "12", "text": "Move forward 12."},
    {"card": "39", "value": "12", "text": "Move forward 12."},
    {"card": "40", "value": "12", "text": "Move forward 12."},
    {"card": "41", "value": "12", "text": "Move forward 12."},
    {"card": "42", "value": "sorry", "text": "Move from start and swithc places with an opponent who you bump back to start."},
    {"card": "43", "value": "sorry", "text": "Move from start and swithc places with an opponent who you bump back to start."},
    {"card": "44", "value": "sorry", "text": "Move from start and swithc places with an opponent who you bump back to start."},
    {"card": "45", "value": "sorry", "text": "Move from start and swithc places with an opponent who you bump back to start."}
]